on:
  push:
    branches:
      - main

permissions:
  packages: write

name: Build & Push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: login ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ragi256
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: docker build
        run: |
          docker build \
          --tag ghcr.io/ragi256/luajit-busted:latest \
          --tag ghcr.io/ragi256/luajit-busted:$(echo ${GITHUB_SHA} | head -c7) \
          .
      - name: docker push
        run: |
          docker push ghcr.io/ragi256/luajit-busted:latest
          docker push ghcr.io/ragi256/luajit-busted:$(echo ${GITHUB_SHA} | head -c7)
